[profile.default]
src = "src"
out = "out"
libs = ["dependencies"]
solc = '0.8.19'
# auto_detect_solc = true

[dependencies]
forge-std = "1.9.5"
"smartcontractkit/chainlink-brownie-contracts" = { version = "1.3.0", git = "https://github.com/smartcontractkit/chainlink-brownie-contracts.git", tag = "1.3.0" }

# See more config options https://github.com/foundry-rs/foundry/blob/master/crates/config/README.md#all-options
