[profile.default]
src = "src"
out = "out"
libs = ["dependencies"]
solc = '0.8.19'
# auto_detect_solc = true

[dependencies]
forge-std = "1.9.5"

# See more config options https://github.com/foundry-rs/foundry/blob/master/crates/config/README.md#all-options
